spring:
  datasource:
    url: jdbc:h2:mem:mvp
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
#        trace: true
springdoc:
  swagger-ui:
    path: /swagger-ui-mvp.html
    operations-sorter: method
